//! Compares `image::tiling` with the ported Idefics3ImageProcessor reference
//! in tests/fixtures/docling (generated by reference/make_docling_fixtures.py;
//! not checked in). Without fixtures these tests pass with a note.
mod common;

use std::path::{Path, PathBuf};

use autopro::image::{ChannelOrder, Filter, TileProcessor};
use common::npy;
use serde_json::Value;

fn fixtures() -> Option<(PathBuf, Value)> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/docling");
    match std::fs::read_to_string(dir.join("manifest.json")) {
        Ok(m) => Some((dir, serde_json::from_str(&m).unwrap())),
        Err(_) => {
            eprintln!("no fixtures; run: cd reference && python make_docling_fixtures.py ../tests/fixtures/docling");
            None
        }
    }
}

#[test]
fn tiling_matches_the_ported_reference() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["tiling"].as_array().unwrap() {
        let image = image::open(dir.join(format!("{}.png", case["image"].as_str().unwrap()))).unwrap();
        let processor = TileProcessor {
            resize_longest_edge: case["resize_longest_edge"].as_u64().unwrap() as u32,
            tile_edge: case["tile_edge"].as_u64().unwrap() as u32,
            filter: Filter::Lanczos,
            do_image_splitting: case["do_image_splitting"].as_bool().unwrap(),
            rescale: Some(1.0 / 255.0),
            normalize: Some(([0.5; 3], [0.5; 3])),
            channel_order: ChannelOrder::Rgb,
        };
        let got = processor.process(&image);
        assert_eq!(got.rows, case["rows"].as_u64().unwrap() as u32, "{}", case["expected"]);
        assert_eq!(got.cols, case["cols"].as_u64().unwrap() as u32, "{}", case["expected"]);

        let want = npy(&dir.join(case["expected"].as_str().unwrap()));
        assert_eq!(want.shape()[0], got.tiles.len(), "{}", case["expected"]);
        for (i, tile) in got.tiles.iter().enumerate() {
            let want_tile = want.index_axis(ndarray::Axis(0), i);
            assert_eq!(tile.shape(), want_tile.shape(), "{} tile {i}", case["expected"]);
            let max = tile.iter().zip(want_tile.iter()).map(|(a, b)| (*a as f64 - b).abs()).fold(0.0, f64::max);
            assert!(max <= 1e-6, "{} tile {i}: max abs diff {max}", case["expected"]);
        }
    }
}
