//! Compares OCR postprocessing with OpenCV, torchvision and PaddleOCR /
//! transformers, from tests/fixtures/ocr (generated by
//! reference/make_ocr_fixtures.py; not checked in). Without fixtures these
//! tests pass with a note.
mod common;

use std::path::{Path, PathBuf};

use autopro::{
    image::resize_bilinear_no_antialias,
    ocr::{DbDecoder, Point, Quad, crop_text_line, fill_poly, find_contours, min_area_rect, sort_boxes},
};
use common::npy;
use image::RgbImage;
use ndarray::{Array2, ArrayD, Ix2};
use serde_json::Value;

fn fixtures() -> Option<(PathBuf, Value)> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/ocr");
    match std::fs::read_to_string(dir.join("manifest.json")) {
        Ok(m) => Some((dir, serde_json::from_str(&m).unwrap())),
        Err(_) => {
            eprintln!("no fixtures; run: cd reference && nix develop .#post --command python make_ocr_fixtures.py ../tests/fixtures/ocr");
            None
        }
    }
}

fn array2(dir: &Path, name: &Value) -> Array2<f64> {
    npy(&dir.join(name.as_str().unwrap())).into_dimensionality::<Ix2>().unwrap()
}

fn rgb(a: &ArrayD<f64>) -> RgbImage {
    let (h, w) = (a.shape()[0], a.shape()[1]);
    RgbImage::from_fn(w as u32, h as u32, |x, y| image::Rgb(std::array::from_fn(|c| a[[y as usize, x as usize, c]] as u8)))
}

fn max_diff(got: &RgbImage, want: &ArrayD<f64>) -> f64 {
    assert_eq!([got.height() as usize, got.width() as usize, 3], want.shape(), "image size");
    got.enumerate_pixels()
        .flat_map(|(x, y, p)| (0..3).map(move |c| (p[c] as f64 - want[[y as usize, x as usize, c]]).abs()))
        .fold(0.0, f64::max)
}

fn points(v: &Value) -> Vec<Point> {
    serde_json::from_value(v.clone()).unwrap()
}

fn quad(v: &Value) -> Quad {
    points(v).try_into().unwrap()
}

#[test]
fn contours_match_opencv() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["contours"].as_array().unwrap() {
        let bitmap = array2(&dir, &case["bitmap"]).mapv(|v| v != 0.0);
        let got = find_contours(bitmap.view());
        let want: Vec<Vec<[i32; 2]>> = serde_json::from_value(case["contours"].clone()).unwrap();
        assert_eq!(got.len(), want.len(), "{}: number of contours", case["bitmap"]);
        for (i, (g, w)) in got.iter().zip(&want).enumerate() {
            assert_eq!(g, w, "{}: contour {i}", case["bitmap"]);
        }
        // Same corners, same order, same float32 rounding.
        let boxes: Vec<Quad> = case["boxes"].as_array().unwrap().iter().map(quad).collect();
        for (i, (c, b)) in got.iter().zip(&boxes).enumerate() {
            let r = min_area_rect(&c.iter().map(|p| [p[0] as f32, p[1] as f32]).collect::<Vec<_>>());
            assert_eq!(&r.corners, b, "{}: contour {i} rectangle", case["bitmap"]);
        }
    }
}

#[test]
fn min_area_rect_matches_opencv() {
    let Some((_, manifest)) = fixtures() else { return };
    let cases = manifest["min_area_rect"].as_array().unwrap();
    let mut ties = 0;
    for case in cases {
        let r = min_area_rect(&points(&case["points"]));
        let want = points(&case["corners"]);
        let same = want.iter().all(|w| {
            let nearest = r.corners.iter().map(|g| (g[0] - w[0]).hypot(g[1] - w[1])).fold(f32::MAX, f32::min);
            nearest < 2e-3 * (1.0 + w[0].abs().max(w[1].abs()))
        });
        let side = |a: Point, b: Point| (a[0] - b[0]).hypot(a[1] - b[1]) as f64;
        let want_area = side(want[0], want[1]) * side(want[1], want[2]);
        let area = r.size[0] as f64 * r.size[1] as f64;
        if !same {
            // Two orientations with (almost) the same area: OpenCV's float32
            // calipers may pick the other one.
            assert!((area - want_area).abs() <= 1e-4 * want_area, "{:?}: {:?} vs {want:?}", case["points"], r.corners);
            ties += 1;
            continue;
        }
        let short = case["short"].as_f64().unwrap() as f32;
        assert!((r.size[0].min(r.size[1]) - short).abs() < 1e-3 * (1.0 + short), "short side {:?} vs {short}", r.size);
    }
    assert!(ties * 50 <= cases.len(), "{ties} ties of {}", cases.len());
}

#[test]
fn fill_poly_matches_opencv() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["fill_poly"].as_array().unwrap() {
        let want = array2(&dir, &case["mask"]).mapv(|v| v as u8);
        let pts: Vec<[i32; 2]> = serde_json::from_value(case["points"].clone()).unwrap();
        let mut got = Array2::zeros(want.dim());
        fill_poly(&mut got, &pts, 1);
        assert_eq!(got, want, "polygon {pts:?}");
    }
}

#[test]
fn db_boxes_match_transformers() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["db"].as_array().unwrap() {
        let prob = array2(&dir, &case["prob"]).mapv(|v| v as f32);
        let f = |k: &str| case[k].as_f64().unwrap() as f32;
        let decoder = DbDecoder { threshold: f("threshold"), box_threshold: f("box_threshold"), unclip_ratio: f("unclip_ratio"), ..DbDecoder::default() };
        let got = decoder.decode(prob.view(), case["width"].as_u64().unwrap() as u32, case["height"].as_u64().unwrap() as u32);
        let want_boxes: Vec<Quad> = case["boxes"].as_array().unwrap().iter().map(quad).collect();
        let want_scores: Vec<f32> = serde_json::from_value(case["scores"].clone()).unwrap();
        let what = format!("{} {decoder:?}", case["prob"]);
        assert_eq!(got.boxes.len(), want_boxes.len(), "{what}: number of boxes");
        for (i, (g, w)) in got.boxes.iter().zip(&want_boxes).enumerate() {
            let d = g.iter().zip(w).map(|(a, b)| (a[0] - b[0]).abs().max((a[1] - b[1]).abs())).fold(0.0, f32::max);
            assert!(d <= 1.0, "{what}: box {i} {g:?} vs {w:?}");
            assert!((got.scores[i] - want_scores[i]).abs() < 1e-5, "{what}: score {i} {} vs {}", got.scores[i], want_scores[i]);
        }
    }
}

#[test]
fn crops_match_paddleocr() {
    let Some((dir, manifest)) = fixtures() else { return };
    let image = rgb(&npy(&dir.join("crop_image.npy")));
    for case in manifest["crops"].as_array().unwrap() {
        let want = npy(&dir.join(case["crop"].as_str().unwrap()));
        let got = crop_text_line(&image, &quad(&case["quad"]));
        assert_eq!([got.height() as usize, got.width() as usize, 3], want.shape(), "{}: size", case["crop"]);
        // Last-bit differences in the homography move a few sample positions
        // to the neighboring 1/32 pixel.
        let diffs: Vec<f64> = got.as_raw().iter().zip(want.iter()).map(|(&a, &b)| (a as f64 - b).abs()).collect();
        let off = diffs.iter().filter(|&&d| d > 0.0).count();
        let max = diffs.iter().copied().fold(0.0, f64::max);
        assert!(max <= 4.0 && off * 500 <= diffs.len(), "{}: {off} of {} values differ, up to {max}", case["crop"], diffs.len());
    }
    for case in manifest["sort"].as_array().unwrap() {
        let quads: Vec<Quad> = case["quads"].as_array().unwrap().iter().map(quad).collect();
        let want: Vec<usize> = serde_json::from_value(case["order"].clone()).unwrap();
        assert_eq!(sort_boxes(&quads), want);
    }
}

#[test]
fn resize_without_antialiasing_matches_torchvision() {
    let Some((dir, manifest)) = fixtures() else { return };
    let image = rgb(&npy(&dir.join("crop_image.npy")));
    for case in manifest["resize"].as_array().unwrap() {
        let want = npy(&dir.join(case["image"].as_str().unwrap()));
        let got = resize_bilinear_no_antialias(&image, case["width"].as_u64().unwrap() as u32, case["height"].as_u64().unwrap() as u32);
        assert_eq!(max_diff(&got, &want), 0.0, "{}", case["image"]);
    }
}
