//! Compares postprocessing with torchvision (NMS, Ultralytics' detector NMS)
//! and scikit-learn (DBSCAN), from tests/fixtures/post (generated by
//! reference/make_post_fixtures.py; not checked in). Without fixtures these
//! tests pass with a note.
mod common;

use std::path::{Path, PathBuf};

use autopro::{
    cluster::{Dbscan, Metric},
    detect::{BoxFormat, Detector, nms},
};
use common::npy;
use ndarray::{Array1, Array2, Ix1, Ix2, s};
use serde_json::Value;

fn fixtures() -> Option<(PathBuf, Value)> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/post");
    match std::fs::read_to_string(dir.join("manifest.json")) {
        Ok(m) => Some((dir, serde_json::from_str(&m).unwrap())),
        Err(_) => {
            eprintln!("no fixtures; run: cd reference && nix develop .#post --command python make_post_fixtures.py ../tests/fixtures/post");
            None
        }
    }
}

fn array2(dir: &Path, name: &str) -> Array2<f32> {
    npy(&dir.join(name)).mapv(|v| v as f32).into_dimensionality::<Ix2>().unwrap()
}

fn array1(dir: &Path, name: &str) -> Array1<f64> {
    npy(&dir.join(name)).into_dimensionality::<Ix1>().unwrap()
}

fn usizes(v: &Value) -> Vec<usize> {
    serde_json::from_value(v.clone()).unwrap()
}

#[test]
fn nms_matches_torchvision() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["nms"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let boxes = array2(&dir, &format!("{name}_boxes.npy"));
        let scores = array1(&dir, &format!("{name}_scores.npy")).mapv(|v| v as f32);
        let classes: Vec<usize> = array1(&dir, &format!("{name}_classes.npy")).iter().map(|&c| c as usize).collect();
        let iou = case["iou"].as_f64().unwrap() as f32;
        let per_class = case["per_class"].as_bool().unwrap();
        let keep = nms(boxes.view(), scores.view(), per_class.then_some(&classes[..]), iou);
        let want = usizes(&case["keep"]);
        assert_eq!(keep, want, "{name} iou {iou}");
    }
}

#[test]
fn detector_matches_ultralytics() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["detector"].as_array().unwrap() {
        // YOLOv8 layout [4 + classes, n].
        let head = array2(&dir, case["head"].as_str().unwrap());
        let rows = head.t();
        let detector = Detector {
            format: BoxFormat::Cxcywh,
            score_threshold: case["score_threshold"].as_f64().unwrap() as f32,
            iou_threshold: case["iou_threshold"].as_f64().unwrap() as f32,
            class_agnostic: case["class_agnostic"].as_bool().unwrap(),
            multi_label: case["multi_label"].as_bool().unwrap(),
            max_detections: case["max_detections"].as_u64().unwrap() as usize,
            ..Detector::default()
        };
        let d = detector.detect(rows.slice(s![.., ..4]), rows.slice(s![.., 4..]));
        let what = format!("{} {detector:?}", case["head"]);
        assert_eq!(d.indices, usizes(&case["indices"]), "{what}");
        assert_eq!(d.classes, usizes(&case["classes"]), "{what}");
        let scores: Vec<f32> = serde_json::from_value(case["scores"].clone()).unwrap();
        assert_eq!(d.scores.to_vec(), scores, "{what}");
        let boxes: Vec<Vec<f32>> = serde_json::from_value(case["boxes"].clone()).unwrap();
        for (got, want) in d.boxes.rows().into_iter().zip(&boxes) {
            // torch computes x - w / 2, we compute x - 0.5 * w: same value.
            assert_eq!(got.to_vec(), *want, "{what}");
        }
        assert!(!d.is_empty());
    }
}

#[test]
fn dbscan_matches_sklearn() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["dbscan"].as_array().unwrap() {
        let x = array2(&dir, case["points"].as_str().unwrap());
        let dbscan = Dbscan {
            eps: case["eps"].as_f64().unwrap(),
            min_samples: case["min_samples"].as_u64().unwrap() as usize,
            metric: Metric::parse(case["metric"].as_str().unwrap()).unwrap(),
        };
        let start = std::time::Instant::now();
        let c = dbscan.fit(x.view());
        let elapsed = start.elapsed();
        let want: Vec<i32> = serde_json::from_value(case["labels"].clone()).unwrap();
        assert_eq!(c.labels.to_vec(), want, "{} {dbscan:?}", case["points"]);
        let core: Vec<usize> = c.core.iter().enumerate().filter(|(_, c)| **c).map(|(i, _)| i).collect();
        assert_eq!(core, usizes(&case["core"]), "{} {dbscan:?}", case["points"]);
        let noise = want.iter().filter(|l| **l < 0).count();
        eprintln!(
            "{} {:?} eps {} min {}: {} clusters, {noise} noise, {elapsed:?}",
            case["points"], dbscan.metric, dbscan.eps, dbscan.min_samples, c.n_clusters
        );
    }
}
