//! Compares autopro with the Hugging Face / Pillow / sentencepiece reference
//! outputs in tests/fixtures (generated by reference/make_fixtures.py; not
//! checked in). Without fixtures these tests pass with a note.
mod common;

use std::path::{Path, PathBuf};

use common::npy;

use autopro::{
    audio::{Audio, WaveformProcessor, WhisperFeatures},
    image::{Filter, ImageProcessor, resize},
    text::{Padding, TextProcessor, Tokenizer},
};
use serde_json::Value;

fn fixtures() -> Option<(PathBuf, Value)> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    match std::fs::read_to_string(dir.join("manifest.json")) {
        Ok(m) => Some((dir, serde_json::from_str(&m).unwrap())),
        Err(_) => {
            eprintln!("no fixtures; run: cd reference && nix develop --command python make_fixtures.py ../tests/fixtures TOKENIZER.model");
            None
        }
    }
}

fn load_image(dir: &Path, name: &str) -> image::DynamicImage {
    image::open(dir.join(format!("{name}.png"))).unwrap()
}

#[test]
fn pillow_resize_is_exact() {
    let Some((dir, manifest)) = fixtures() else { return };
    let mut failures = Vec::new();
    for case in manifest["resize"].as_array().unwrap() {
        let rgb = load_image(&dir, case["image"].as_str().unwrap()).to_rgb8();
        let filter = Filter::parse(case["filter"].as_str().unwrap()).unwrap();
        let (w, h) = (case["width"].as_u64().unwrap() as u32, case["height"].as_u64().unwrap() as u32);
        let got = resize(&rgb, w, h, filter);
        let want = npy(&dir.join(case["expected"].as_str().unwrap()));
        assert_eq!(got.as_raw().len(), want.len(), "{}", case["expected"]);
        assert_eq!(want.shape(), &[h as usize, w as usize, 3]);
        let diff = got.as_raw().iter().zip(want.iter()).filter(|(a, b)| **a as f64 != **b).count();
        if diff > 0 {
            failures.push(format!("{} {:?} {w}x{h}: {diff} bytes differ", case["image"], filter));
        }
    }
    assert!(failures.is_empty(), "{failures:#?}");
    eprintln!("{} resize cases bit-exact", manifest["resize"].as_array().unwrap().len());
}

#[test]
fn image_processors_match_hf() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["processors"].as_array().unwrap() {
        let processor = ImageProcessor::from_hf_config(&case["config"]).unwrap();
        let got = processor.process(&load_image(&dir, case["image"].as_str().unwrap()));
        let want = npy(&dir.join(case["expected"].as_str().unwrap()));
        assert_eq!(got.shape(), want.shape(), "{}", case["expected"]);
        assert!(!got.is_empty());
        let max = got.iter().zip(want.iter()).map(|(a, b)| (*a as f64 - b).abs()).fold(0.0, f64::max);
        assert!(max <= 1e-6, "{}: max abs diff {max}", case["expected"]);
    }
}

#[test]
fn sentencepiece_matches_the_library() {
    let Some((dir, manifest)) = fixtures() else { return };
    let mut failures = Vec::new();
    for case in manifest["sentencepiece"].as_array().unwrap() {
        let Tokenizer::SentencePiece(sp) = Tokenizer::from_file(dir.join(case["model"].as_str().unwrap())).unwrap() else {
            panic!("not detected as sentencepiece")
        };
        let text = case["text"].as_str().unwrap();
        let got = sp.encode(text, case["add_bos"].as_bool().unwrap(), case["add_eos"].as_bool().unwrap());
        let want: Vec<u32> = serde_json::from_value(case["ids"].clone()).unwrap();
        if got != want {
            failures.push(format!("{} {text:?}\n  got  {got:?}\n  want {want:?}\n  normalized {:?}", case["model"], sp.normalize(text)));
        }
        let decoded = sp.decode(&want, true);
        if decoded != case["decoded"].as_str().unwrap() {
            failures.push(format!("{} decode {want:?}\n  got  {decoded:?}\n  want {:?}", case["model"], case["decoded"]));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
    eprintln!("{} sentencepiece cases identical", manifest["sentencepiece"].as_array().unwrap().len());
}

#[test]
fn tokenizer_json_matches_hf() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["tokenizers"].as_array().unwrap() {
        let file = dir.join(case["tokenizer"].as_str().unwrap());
        let text = case["text"].as_str().unwrap();
        let special = case["add_special_tokens"].as_bool().unwrap();
        let tokenizer = Tokenizer::from_file(&file).unwrap();
        let want: Vec<u32> = serde_json::from_value(case["ids"].clone()).unwrap();
        assert_eq!(tokenizer.encode(text, special).unwrap(), want, "{file:?} {text:?}");
        let ids: Vec<u32> = want.clone();
        assert_eq!(tokenizer.decode(&ids, true).unwrap(), case["decoded"].as_str().unwrap(), "decode {file:?} {text:?}");

        let mut processor = TextProcessor::new(Tokenizer::from_file(&file).unwrap());
        processor.options.add_special_tokens = special;
        processor.options.padding = Padding::Fixed(8);
        let enc = processor.encode_batch(&[text]).unwrap();
        let want_ids: Vec<i64> = serde_json::from_value(case["max_length_8"]["ids"].clone()).unwrap();
        let want_mask: Vec<i64> = serde_json::from_value(case["max_length_8"]["attention_mask"].clone()).unwrap();
        assert_eq!(enc.ids.row(0).to_vec(), want_ids, "truncated/padded ids {file:?} {text:?} special={special}");
        assert_eq!(enc.attention_mask.row(0).to_vec(), want_mask, "mask {file:?} {text:?}");
    }
}

#[test]
fn audio_features_match_hf() {
    let Some((dir, manifest)) = fixtures() else { return };
    for case in manifest["audio"].as_array().unwrap() {
        let audio = Audio::from_wav_file(dir.join(case["wav"].as_str().unwrap())).unwrap();
        let want = npy(&dir.join(case["expected"].as_str().unwrap()));
        match case["kind"].as_str().unwrap() {
            "whisper" => {
                let got = WhisperFeatures::new(case["n_mels"].as_u64().unwrap() as usize).compute(&audio.samples);
                assert_eq!(got.shape(), want.shape());
                let max = got.iter().zip(want.iter()).map(|(a, b)| (*a as f64 - b).abs()).fold(0.0, f64::max);
                assert!(max < 1e-4, "whisper {}: max abs diff {max}", case["n_mels"]);
            }
            "wav2vec2" => {
                let processor = WaveformProcessor {
                    sample_rate: 16000,
                    normalize: true,
                    length: Some(case["length"].as_u64().unwrap() as usize),
                    padding_value: 0.0,
                };
                let (values, mask) = processor.process(&audio).unwrap();
                let max = values.iter().zip(want.iter()).map(|(a, b)| (*a as f64 - b).abs()).fold(0.0, f64::max);
                assert!(max < 1e-5, "wav2vec2 max abs diff {max}");
                let want_mask = npy(&dir.join(case["mask"].as_str().unwrap()));
                assert!(mask.iter().zip(want_mask.iter()).all(|(a, b)| *a as f64 == *b));
            }
            other => panic!("unknown audio case {other}"),
        }
    }
}
